### ISSUE TITLE
dataset_loader.py

### ISSUE THREAD

**Issue by mathislinger** [Priberam/news-clustering#2]
Hello,

While testing your code, it seems that dataset_loader.py is not available.
Is it missing or under another name?

Thank you :)

**Comment by celinelimsy** [comment]
Hi, I am having the same problem as well. May I know where I can find dataset_loader.py?

Thank you!

**Comment by smiranda** [comment]
Sorry, this file was in fact removed by mistake. 
I've re-added it in commit f5174cf3a1f2f68934022d119a06c0c521ed9d6d , already merged to master.
