### ISSUE TITLE
cannot download data

### ISSUE THREAD

**Issue by brotherb** [Priberam/news-clustering#4]
Hi. 
Thanks for this wonderful dataset. However, I can not download it from the URLs in download_data.sh. Can you provide a new download URL?

**Comment by smiranda** [comment]
Hello they should be working. Which error do you get ?

**Comment by brotherb** [comment]
> Hello they should be working. Which error do you get ?
Thanks for your reply. 
I figured out that my server have some network issues. I can download them now.

**Comment by smiranda** [comment]
Hello, you re-opened the issue. For any reason ?
