### ISSUE TITLE
RELEVANCE_TS feature issue

### ISSUE THREAD

**Issue by brotherb** [Priberam/news-clustering#5]
Hi

In clustering.py, line 49, I saw
`bof["RELEVANCE_TS"] = timestamp_feature(d0.timestamp.timestamp(), c1.get_relevance_stamp(), numdays_stddev)`
This feature always gives 0.0. I suppose this is a bug, since `c1.get_relevance_stamp()`  returns `mean = self.sum_timestamp / self.num_docs`, which is in hour.
At the meantime, the timestamp feature of average timestamp of a cluster mentioned in paper is missing. Is 'RELEVANCE_TS' feature suppose to be that feature?

**Comment by smiranda** [comment]
Hello,

Yes, that should be same feature, not sure why i gave that name. In fact it uses the average timestamp of the cluster. 

If you think there's a bug, you can try to put both timestamp values in the same type (hour/day) and see if it makes sense.
