### ISSUE TITLE
Can you provide instructions for generating merging samples?

### ISSUE THREAD

**Issue by brotherb** [Priberam/news-clustering#6]
Hi, recently I am reproducing the experimental results of this paper.

I have retrained the news-cluster similarity ranking model, and replace the provided ranking model but keep svm-merge model unchanged. And the bcubed P/R/F1 is  93.81 | 96.74 | 95.25, which is higher than this paper (94.57 | 90.25 | 92.36). 

However I have issue reproducing the svm-merge model. I wonder if my sample generation procedures are right.  

Here's my code:

`class MergeAggregator:
    def __init__(self, cids, sim_model):
        self.cids = cids
        self.sim_model = sim_model
        self.clusters = {}
        for cid in cids:
            self.clusters[cid] = Cluster(cid)

    def PutDocument(self, document):
        k = 1
        cid = document.cid
        feat = None
        label = None
        if self.clusters[cid].num_docs == 0:
            # should create new cluster
            # choose topK (k=1) most similar cluster and assign False(-1) label
            sim_clusters = [(cluster.cid, sim_bof_dc(document, cluster)) for cluster in self.clusters.values() if
                            cluster.num_docs != 0 and cluster.cid != cid]
            if len(sim_clusters) == 0:
                self.clusters[cid].add_document(document)
                return None, None
            sim_clusters = [(t[0], t[1], model_score(t[1], self.sim_model)) for t in sim_clusters]
            sim_clusters = sorted(sim_clusters, key=lambda x:-x[2])
            feat = [t[1] for t in sim_clusters[:k]]
            label = -1
        else:
            # should merge to existing cluster
            # choose groud-truth cluster and assign True(1) label
            feat = sim_bof_dc(document, self.clusters[cid])
            label = 1
        self.clusters[cid].add_document(document)
        return label, feat
def gen_merge_data():
    feat2id = {
        'Entities_all': 1,
        'Entities_body': 2,
        'Entities_title': 3,
        'Lemmas_all': 4,
        'Lemmas_body': 5,
        'Lemmas_title': 6,
        'NEWEST_TS': 7,
        'OLDEST_TS': 8,
        'AVERAGE_TS': 9,
        'Tokens_all': 10,
        'Tokens_body': 11,
        'Tokens_title': 12,
        'ZZINVCLUSTER_SIZE': 13
    }
    lang = 'eng'
    corpus = load_corpora.load(r"dataset/en.dev.json",
                               r"dataset/en.clustering.dev.json", {lang})
    print(lang, "#docs", len(corpus.documents))
    cids = set([d['cluster'] for d in corpus.documents])
    sim_model = model.Model()
    # load trained similarity ranking model
    sim_model.load(r'sim.model', r'sim.featmap')
    aggregator = MergeAggregator(cids, sim_model)

    # simulate clustering
    for i, d in enumerate(corpus.documents):
        # print('\r', i, "/", len(corpus.documents),
        #       " | #c= ", len(aggregator.clusters), end="")
        label, feats = aggregator.PutDocument(Document(d, "???"))
        if label == None:
            continue
        if label == 1:
            #positive sample
            feat = feats
            feat = [(feat2id[k], v) for k, v in feat.items()]
            feat = sorted(feat, key=lambda x: x[0])
            print('%d %s' % (label, ' '.join(['%d:%f' % (k, v) for k, v in feat])))
        else:
            #negative sample
            for feat in feats:
                feat = [(feat2id[k], v) for k, v in feat.items()]
                feat = sorted(feat, key=lambda x: x[0])
                print('%d %s' % (label, ' '.join(['%d:%f' % (k, v) for k, v in feat])))
`

The generated samples are imbalanced since there are more than 11k merges and only 590+ new cluster creations. The trained model stops creating new clusters after some time. I use liblinear and the default linsear svm classifier. 

I will keep checking my code to see where the error occurs.

**Comment by brotherb** [comment]
By the way, in your paper, you describe the input feature of svm-merge model as:

> by passing the max of the similarity of each feature between the incoming document and the current clustering pool as the input feature vector

I guess this suppose to be feature-level max pooling over all the news-cluster pairs of existing clusters.
But in this code, the input feature is the similarity features of the incoming document and the top1 cluster rank by the ranking model. Did I miss the point?

**Comment by brotherb** [comment]
I have reproduced this method.

**Comment by smiranda** [comment]
Thank you !
