### ISSUE TITLE
handling model bias

### ISSUE THREAD

**Issue by hjian42** [Priberam/news-clustering#7]
Hey, I have a question about the implementation here

https://github.com/Priberam/news-clustering/blob/95931a56937cd29b1e742b644ec4a713a1943703/clustering.py#L56

I am wondering why this is a "-" instead of "+"? 

Also, I notice that all the released models have bias=0, so it might not make a difference when you initialize models with bias=0.

**Comment by smiranda** [comment]
Hello, well yes specially if bias=0 then the signal is not relevant. But that signal depends on the svm implementation that gave you the weights. Honestly, i don't remember.

**Comment by hjian42** [comment]
Thanks for your reply! 

However, I use the SVM-rank and SVM-liblinear libraries that this paper used. These libraries seem to just save the bias (either a negative or positive number) in the saved model format. So my intuition is that this should be a +.
